### ISSUE TITLE
countries_data.json not generated

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft-shop#9] opened 2018-01-18 09:56 UTC
After `yarn start` I get:
`ERROR in ./src/lib/countries.js`
`Module not found: Error: Can't resolve './countries_data.json' in 'foodsoft-shop/src/lib'`

**Comment by wvengen** [comment] 2018-01-19 09:25
Note that this is file is generated from [countries_data.js](https://github.com/foodcoops/foodsoft-shop/blob/7e485d4f4d2a35bc697d67630a78fbd7a864c841/src/lib/countries_data.js) in [webpack.config.js](https://github.com/foodcoops/foodsoft-shop/blob/master/webpack.config.js#L45).
I haven't run this for quite a while, it might be possible that things have changed since with webpack.

**Comment by wvengen** [comment] 2018-03-28 19:50
Still works for me. What node version are you using (mine is v8.9.4)?

**Comment by wvengen** [comment] 2018-10-12 16:42
I can't reproduce this, closing. Please feel free to reopen when this problem happens again.

**Comment by wvengen** [comment] 2018-10-12 16:45
Ah, running `npm upgrade` gives me this error as well. On it!

**Closed** 2018-10-12 17:02 UTC
Labels: bug
